import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IRootLayout {
  children: Readonly<React.ReactNode>;
}

export default function RootLayout({ children }: IRootLayout) {

  const classes = `h-screen ${inter.className}`;

  return (
    <html lang="en">
      <body className={classes}>
        <div className='h-full px-12 py-4'>
          {children}
        </div>
      </body>
    </html>
  );
}
